### ISSUE TITLE
chapter 10 gazebo sonar does not work

### ISSUE THREAD

**Issue by woofer46** [qboticslabs/ros_robotics_projects#16]
Hi,
I use code example following your book, so when I start
`roslaunch sensor_sim_gazebo sonar.launch`
I do not see /distance topic by rostopic list, but in gazebo and rviz I see model of sonar sensor
I use ros kinetic and gazebo 7
Which version of gazebo do you use?

**Comment by qboticslabs** [comment]
Hello

Can you put the terminal screenshot here? Is it throwing any error in terminal? You should install the hector gazebo plugin in order to enable ultrasonic plugin

**Comment by woofer46** [comment]
Hello,
Thank you!
When I was reading the book I forgot to install hector gazebo plugin. 
By the way, before the installation my screenshot was:
![before](https://user-images.githubusercontent.com/13292653/53390514-7319c800-39a4-11e9-885b-c3a4c68af698.png)
